import { StyleSheet } from 'react-native';
import { colors } from '../../colors';
import { fontFamily } from '../../font-family';
import { fontSizes } from '../../font-sizes';

export const styles = StyleSheet.create({
  container: {
    position: 'relative',
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 24,
    backgroundColor: colors.white,
  },
  scrollContent: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 24,
    paddingVertical: 40,
  },
  logo: {
    position: 'relative',
    marginBottom: 80,
    width: 300,
    height: 60,
    resizeMode: 'contain',
  },
  content: {
    width: '100%',
    maxWidth: 400,
    alignItems: 'center',
    gap: 12,
  },
  topContentView: {
    gap: 3,
  },
  title: {
    fontSize: fontSizes.extraExtraLarge,
    fontFamily: fontFamily.ManropeBold,
    color: colors.black,
    marginBottom: 12,
    textAlign: 'center',
  },
  subtitle: {
    fontSize: fontSizes.medium,
    fontFamily: fontFamily.ManropeRegular,
    color: colors.gray600,
    textAlign: 'center',
    marginBottom: 48,
    lineHeight: 24,
  },
  authButton: {
    position: 'relative',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.white,
    paddingVertical: 16,
    paddingHorizontal: 24,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: colors.gray200,
    width: '100%',
    shadowColor: colors.shadow,
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 2,
  },
  authButtonText: {
    color: colors.black,
    fontSize: fontSizes.base,
    fontFamily: fontFamily.ManropeSemiBold,
    marginLeft: 12,
  },
  iconContainer: {
    width: 24,
    height: 24,
    justifyContent: 'center',
    alignItems: 'center',
  },
  emailSection: {
    width: '100%',
    marginTop: 8,
  },
  dividerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 12,
    marginTop: 20,
    width: '80%',
    marginHorizontal: 'auto',
  },
  dividerLine: {
    flex: 1,
    height: 1,
    backgroundColor: colors.gray300,
  },
  dividerText: {
    fontFamily: fontFamily.ManropeRegular,
    fontSize: fontSizes.extraSmall,
    color: colors.black,
  },
  label: {
    fontFamily: fontFamily.ManropeSemiBold,
    fontSize: fontSizes.medium,
    color: colors.black,
    marginTop: 16,
    marginBottom: 6,
  },
  input: {
    borderWidth: 1,
    borderColor: colors.gray200,
    borderRadius: 12,
    paddingVertical: 14,
    paddingHorizontal: 16,
    fontSize: fontSizes.base,
    fontFamily: fontFamily.ManropeRegular,
    backgroundColor: colors.white,
    color: colors.black,
  },
  passwordLabelContainer: {
    marginTop: 20,
    marginBottom: 6,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  passwordLabel: {
    fontFamily: fontFamily.ManropeSemiBold,
    fontSize: fontSizes.medium,
    color: colors.black,
  },
  forgotPasswordText: {
    fontFamily: fontFamily.ManropeSemiBold,
    fontSize: fontSizes.small,
    color: colors.gray500,
    textDecorationLine: 'underline',
  },
  passwordContainer: {
    position: 'relative',
    width: '100%',
  },
  passwordInput: {
    borderWidth: 1,
    borderColor: colors.gray200,
    borderRadius: 12,
    paddingVertical: 14,
    paddingHorizontal: 16,
    paddingRight: 48,
    fontSize: fontSizes.base,
    fontFamily: fontFamily.ManropeRegular,
    backgroundColor: colors.white,
    color: colors.black,
  },
  eyeButton: {
    position: 'absolute',
    right: 12,
    top: 18,
    padding: 4,
  },
  errorText: {
    fontFamily: fontFamily.ManropeRegular,
    fontSize: fontSizes.medium,
    color: colors.error,
    marginTop: 12,
    marginBottom: 4,
    textAlign: 'center',
  },
  emailButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.black,
    paddingVertical: 16,
    paddingHorizontal: 24,
    borderRadius: 12,
    width: '100%',
    marginTop: 20,
    minHeight: 52,
  },
  emailButtonDisabled: {
    opacity: 0.6,
  },
  emailButtonContent: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  emailButtonText: {
    color: colors.white,
    fontSize: fontSizes.base,
    fontFamily: fontFamily.ManropeSemiBold,
  },
  linkContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 20,
    gap: 4,
  },
  linkPrompt: {
    fontFamily: fontFamily.ManropeRegular,
    fontSize: fontSizes.small,
    color: colors.gray600,
  },
  linkText: {
    fontFamily: fontFamily.ManropeSemiBold,
    fontSize: fontSizes.small,
    color: colors.primaryBlue,
  },
  backLink: {
    alignSelf: 'center',
    marginTop: 24,
  },
});
